# Generated by Django 5.0.4 on 2024-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path', models.ImageField(blank=True, upload_to='img/%Y/%m/%d/')),
                ('description', models.TextField()),
            ],
        ),
    ]
