# Generated by Django 5.0.4 on 2024-07-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='item',
        ),
    ]
