# Generated by Django 5.0.7 on 2024-07-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_comment_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
